name: Update M3U File (No Commit History)

on:
  schedule:
    # Run every 5 hours
    - cron: "0 */5 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Download the M3U file with tvg-id=false and rename it
      - name: Download M3U File with tvg-id=false
        run: |
          curl -L "https://4tt220.unlimitedtvsolution.workers.dev/playlist?tvg-id=false" -o tva.txt

      # Step 3: Download the M3U file with tvg-id=true and rename it
      - name: Download M3U File with tvg-id=true
        run: |
          curl -L "https://4tt220.unlimitedtvsolution.workers.dev/playlist?tvg-id=true" -o tvawe.txt
          
      # Step 4: Force replace the file and push
      - name: Replace and Force Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tva.txt tvawe.txt
          git commit --amend --no-edit || git commit -m "Update files"
          git push --force
